name: 'build-test'
on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        container:
          - fedora
          - debian
          - opensuse/leap
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - name: prepare package.json
        run: |
          echo '{ "packageManager": "pnpm@8.15.3" }' >package.json
      - run: id
      - uses: pnpm/action-setup@v2
      - run: id
